%ifndef _gtk_inc_
%define _gtk_inc_

%define GTK_WIN_POS_CENTER 1
%define GTK_WIN_WIDTH 700
%define GTK_WIN_HEIGHT 450

extern _exit
extern _gtk_init
extern _gtk_main
extern _g_object_set
extern _gtk_main_quit
extern _gtk_window_new
extern _gtk_widget_show
extern _g_signal_connect
extern _gtk_window_set_title
extern _g_signal_connect_data
extern _gtk_window_set_position
extern _gtk_settings_get_default
extern _gtk_widget_set_size_request
extern _gtk_window_set_default_size

%endif      ; _gtk_inc_